name: Deploy Changed Microservices to AWS ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Detect Changed Services
        id: changes
        run: |
          echo "Detecting changed services..."

          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual workflow detected."
            echo "changed=ALL" >> $GITHUB_OUTPUT
            exit 0
          fi

          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

          echo "Changed files:"
          echo "$CHANGED_FILES"

          CHANGED_SERVICES=$(echo "$CHANGED_FILES" | grep '^services/' | cut -d'/' -f2 | sort -u | tr '\n' ' ')

          if [ -z "$CHANGED_SERVICES" ]; then
            echo "No microservice changes detected."
            echo "changed=NONE" >> $GITHUB_OUTPUT
          else
            echo "Changed services: $CHANGED_SERVICES"
            echo "changed=$CHANGED_SERVICES" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Changed Images
        if: steps.changes.outputs.changed != 'NONE'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |

          declare -A REPOS

          REPOS["gateway-service"]="psm-gateway-service"
          REPOS["academic-service"]="psm-academic-service"
          REPOS["library-service"]="psm-library-service"
          REPOS["inventory-service"]="psm-inventory-service"
          REPOS["scheduling-service"]="psm-scheduling-service"
          REPOS["finance-service"]="psm-finance-service"
          REPOS["cafe-service"]="psm-cafe-service"
          REPOS["assignment-quiz-service"]="psm-assignment-quiz-service"
          REPOS["research-lab-service"]="psm-research-lab-service"
          REPOS["parking-alumni-service"]="psm-parking-alumni-service"
          REPOS["report-service"]="psm-report-service"

          if [ "${{ steps.changes.outputs.changed }}" = "ALL" ]; then
            SERVICES="${!REPOS[@]}"
          else
            SERVICES="${{ steps.changes.outputs.changed }}"
          fi

          for SERVICE in $SERVICES
          do
            REPO=${REPOS[$SERVICE]}

            echo "----------------------------------------"
            echo "Building: $SERVICE"
            echo "Repository: $REPO"
            echo "----------------------------------------"

            docker build \
              -t $ECR_REGISTRY/$REPO:latest \
              -f ./services/$SERVICE/Dockerfile \
              ./services/$SERVICE

            docker push $ECR_REGISTRY/$REPO:latest

            echo "$SERVICE deployed successfully."
          done

      - name: No Services Changed
        if: steps.changes.outputs.changed == 'NONE'
        run: |
          echo "No microservice changes detected."
          echo "Skipping Docker build and push."